### ISSUE TITLE
(NOT REALLY AN ISSUE) My discord name I guess…?

### ISSUE THREAD

**Issue by Wither362** [fnbrco/translations#159]
Well… I don't know if I should make an issue specifying my discord name… but here it is:

**Wither#978**

And my [fnbr.co](https://fnbr.co) account is **Wither**

(Sorry for the issue, I don't know how to tell it to you)

**Comment by Krymonota** [comment]
Don't worry, I haven't forgotten 🙂 I get notifications for everything that happens in this repository. I might just need some time to reply because I work on this project voluntarily.

Let's continue the conversation here: https://github.com/fnbrco/translations/pull/157#issuecomment-1376119156
